# Description: Docker Compose file for development environment
# Author: Sebastián Gámez Ariza

version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/home/app
